//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SBResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SBResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Services.SBResource", typeof(SBResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	DECLARE @BrokerEnabled BIT; 
        ///	SELECT @BrokerEnabled = is_broker_enabled from sys.databases db where db.database_id = DB_ID()
        ///	if (@BrokerEnabled = 0)
        ///	BEGIN
        ///		DECLARE @DynamicSql NVARCHAR(MAX) = N&apos;ALTER DATABASE [&apos; +  DB_NAME() + &apos;] SET ENABLE_BROKER WITH ROLLBACK IMMEDIATE&apos;
        ///		EXEC sp_executesql @DynamicSql; 
        ///		SET @DynamicSql = N&apos;ALTER DATABASE [&apos; +  DB_NAME() + &apos;] SET NEW_BROKER WITH ROLLBACK IMMEDIATE&apos;
        ///		EXEC sp_executesql @DynamicSql; 
        ///	END;
        ///.
        /// </summary>
        internal static string cmd_EnableSB {
            get {
                return ResourceManager.GetString("cmd_EnableSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @DynamicSql NVARCHAR(MAX) = &apos;
        ///	CREATE PROCEDURE sp_Drop_ActivationProcedure
        ///		@ActivationProcedureName AS NVARCHAR(MAX)
        ///	AS
        ///	BEGIN	
        ///		SET NOCOUNT ON;
        ///		IF (@ActivationProcedureName = &apos;&apos;&apos;&apos;) 
        ///		BEGIN
        ///			RETURN;
        ///		END;
        ///		DECLARE @DynamicSqlTemplate as NVARCHAR(MAX) = N&apos;&apos;
        ///		IF OBJECT_ID(&apos;&apos;&apos;&apos;#ActivationProcedureName#&apos;&apos;&apos;&apos;, &apos;&apos;&apos;&apos;P&apos;&apos;&apos;&apos;) IS NOT NULL 
        ///		BEGIN
        ///			DROP PROCEDURE [#ActivationProcedureName#];
        ///		END;&apos;&apos;
        ///		EXECUTE sp_executesql @DynamicSql
        ///	END;&apos;
        ///EXEC sp_executesql @DynamicSql
        ///
        ///SET [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sp_Create_ConfigurationSP {
            get {
                return ResourceManager.GetString("sp_Create_ConfigurationSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///IF OBJECT_ID(&apos;sp_Create_ActivationProcedure&apos;) IS NOT NULL
        ///BEGIN
        ///	DROP PROCEDURE sp_Create_ActivationProcedure;
        ///END
        ///
        ///IF OBJECT_ID(&apos;sp_Create_MessageType&apos;) IS NOT NULL
        ///BEGIN
        ///	DROP PROCEDURE sp_Create_MessageType;
        ///END
        ///
        ///IF OBJECT_ID(&apos;sp_Create_Contract&apos;) IS NOT NULL
        ///BEGIN
        ///	DROP PROCEDURE sp_Create_Contract;
        ///END
        ///
        ///IF OBJECT_ID(&apos;sp_Create_ErrorLogTable&apos;) IS NOT NULL
        ///BEGIN
        ///	DROP PROCEDURE sp_Create_ErrorLogTable;
        ///END
        ///
        ///IF OBJECT_ID(&apos;sp_Create_ErrorLogTable&apos;) IS NOT NULL
        ///BEGIN
        ///	DROP PROCEDURE  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sp_Drop_ConfigurationSP {
            get {
                return ResourceManager.GetString("sp_Drop_ConfigurationSP", resourceCulture);
            }
        }
    }
}
